transilien:
  stations:
    departure: 00000000
    arrival: 00000000
  credentials:
    username: username
    password: password

refresh_time: 10

display:
  type: lcd
  lcd-config:
    columns: 16
    rows: 2
